### PR TITLE
Animals branch milestone.

### PR DESCRIPTION
**Pull request by Nowembabazi**
##In this milestone i achieved the following;
-Create tables in SQL.
-Insert and query data in SQL.
Screenshot from 2023-01-04 10-10-14
Screenshot from 2023-01-04 10-10-54
Screenshot from 2023-01-04 10-12-01
image
image
image
image
image
image
Screenshot from 2023-01-04 11-53-31
Screenshot from 2023-01-04 11-54-02

### CODE REVIEW

**Review by alexander16108 — CHANGES_REQUESTED** [review]
Hi @Nowembabazi , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## To Highlight
✅ You used the correct Github flow
✅ screenshots ok


## Required Changes ♻️
_Check the comments under the review._

-   you have not added a screenshot that should show the following query please add them and try again
       - `SELECT * FROM animals WHERE name LIKE '%mon';`
       - `SELECT * FROM animals WHERE neutered = 'true';`
       - `SELECT * FROM animals WHERE name <> 'Gabumon';`
       - `SELECT name FROM animals WHERE neutered = 'true' AND escape_attempts < '3';`

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by tufoinnkuo10 — CHANGES_REQUESTED** [review]
Hi @Nowembabazi 

nice job adding some of the previous reviewer's changes. There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ screenshots ok

Required Changes ♻️
please you are still missing some of the query screenshots which helps to ensure that you ran the queries with success. you are missing for; 
- it can find all animals that its name ends in "mon".

```sql
SELECT * FROM animals WHERE name LIKE '%mon'; 
```
- it can find all animals not named Gabumon.

```sql
SELECT * FROM animals WHERE name <> 'Gabumon';
```
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Review by alexander16108 — CHANGES_REQUESTED** [review]
Hi @Nowembabazi , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## To Highlight
✅ You used the correct GitHub flow
✅ screenshots ok


 ## Required Changes ♻️
_Check the comments under the review._

please you are still missing some of the query screenshots which helps to ensure that you ran the queries with success. you are missing for;

- it can find all animals whose names ends in "mon".
`SELECT * FROM animals WHERE name LIKE '%mon'; `

N.B ⏫ it has more than one character in the result of this query 😄 

- it can find all animals not named Gabumon.
`SELECT * FROM animals WHERE name <> 'Gabumon';`

N.B ⏫ it has more than one character in the result of this query 😄 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by alexander16108 — APPROVED** [review]
Hi @Nowembabazi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
